"""Initial migration

Revision ID: ca2beb40bc2c
Revises: 
Create Date: 2026-01-22 17:09:38.393825+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ca2beb40bc2c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campus',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_campus_code'), 'campus', ['code'], unique=True)
    op.create_index(op.f('ix_campus_id'), 'campus', ['id'], unique=False)
    op.create_index(op.f('ix_campus_is_active'), 'campus', ['is_active'], unique=False)
    op.create_table('guardian',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardian_document_number'), 'guardian', ['document_number'], unique=False)
    op.create_index(op.f('ix_guardian_id'), 'guardian', ['id'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=False)
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('schoolyear',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_schoolyear_id'), 'schoolyear', ['id'], unique=False)
    op.create_index(op.f('ix_schoolyear_is_current'), 'schoolyear', ['is_current'], unique=False)
    op.create_table('subject',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subject_code'), 'subject', ['code'], unique=True)
    op.create_index(op.f('ix_subject_id'), 'subject', ['id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('coursegroup',
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=10), nullable=True),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coursegroup_campus_id'), 'coursegroup', ['campus_id'], unique=False)
    op.create_index(op.f('ix_coursegroup_id'), 'coursegroup', ['id'], unique=False)
    op.create_index(op.f('ix_coursegroup_school_year_id'), 'coursegroup', ['school_year_id'], unique=False)
    op.create_table('idcardtemplate',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('card_type', sa.Enum('STUDENT', 'TEACHER', name='cardtype'), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('css_styles', sa.Text(), nullable=True),
    sa.Column('fields_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idcardtemplate_id'), 'idcardtemplate', ['id'], unique=False)
    op.create_table('period',
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyear.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_id'), 'period', ['id'], unique=False)
    op.create_index(op.f('ix_period_school_year_id'), 'period', ['school_year_id'], unique=False)
    op.create_table('settings',
    sa.Column('campus_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campus_id', 'key', name='uq_campus_key')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_table('student',
    sa.Column('student_code', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=True),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('blood_type', sa.String(length=10), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_campus_id'), 'student', ['campus_id'], unique=False)
    op.create_index(op.f('ix_student_document_number'), 'student', ['document_number'], unique=False)
    op.create_index(op.f('ix_student_id'), 'student', ['id'], unique=False)
    op.create_index(op.f('ix_student_is_active'), 'student', ['is_active'], unique=False)
    op.create_index(op.f('ix_student_student_code'), 'student', ['student_code'], unique=True)
    op.create_table('teacher',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('teacher_code', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_id'), 'teacher', ['id'], unique=False)
    op.create_index(op.f('ix_teacher_teacher_code'), 'teacher', ['teacher_code'], unique=True)
    op.create_index(op.f('ix_teacher_user_id'), 'teacher', ['user_id'], unique=True)
    op.create_table('user_campus',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campus_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_campus_campus_id'), 'user_campus', ['campus_id'], unique=False)
    op.create_index(op.f('ix_user_campus_id'), 'user_campus', ['id'], unique=False)
    op.create_index(op.f('ix_user_campus_user_id'), 'user_campus', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_id'), 'user_role', ['id'], unique=False)
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('enrollment',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('course_group_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('enrollment_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'TRANSFERRED', 'WITHDRAWN', name='enrollmentstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_group_id'], ['coursegroup.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyear.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollment_course_group_id'), 'enrollment', ['course_group_id'], unique=False)
    op.create_index(op.f('ix_enrollment_id'), 'enrollment', ['id'], unique=False)
    op.create_index(op.f('ix_enrollment_school_year_id'), 'enrollment', ['school_year_id'], unique=False)
    op.create_index(op.f('ix_enrollment_status'), 'enrollment', ['status'], unique=False)
    op.create_index(op.f('ix_enrollment_student_id'), 'enrollment', ['student_id'], unique=False)
    op.create_table('idcardissued',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('card_number', sa.String(length=50), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('pdf_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('issued_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['idcardtemplate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_idcardissued_card_number'), 'idcardissued', ['card_number'], unique=True)
    op.create_index(op.f('ix_idcardissued_id'), 'idcardissued', ['id'], unique=False)
    op.create_index(op.f('ix_idcardissued_is_active'), 'idcardissued', ['is_active'], unique=False)
    op.create_table('student_guardian',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('PADRE', 'MADRE', 'ACUDIENTE', 'OTRO', name='relationshiptype'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_authorized_pickup', sa.Boolean(), nullable=False),
    sa.Column('lives_with', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardian.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardian_guardian_id'), 'student_guardian', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_student_guardian_id'), 'student_guardian', ['id'], unique=False)
    op.create_index(op.f('ix_student_guardian_student_id'), 'student_guardian', ['student_id'], unique=False)
    op.create_table('teacherassignment',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('course_group_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('school_year_id', sa.UUID(), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('assigned_at', sa.Date(), nullable=False),
    sa.Column('ended_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_group_id'], ['coursegroup.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyear.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacherassignment_course_group_id'), 'teacherassignment', ['course_group_id'], unique=False)
    op.create_index(op.f('ix_teacherassignment_id'), 'teacherassignment', ['id'], unique=False)
    op.create_index(op.f('ix_teacherassignment_school_year_id'), 'teacherassignment', ['school_year_id'], unique=False)
    op.create_index(op.f('ix_teacherassignment_subject_id'), 'teacherassignment', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacherassignment_teacher_id'), 'teacherassignment', ['teacher_id'], unique=False)
    op.create_table('classsession',
    sa.Column('course_group_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('teacher_assignment_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('period_id', sa.UUID(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'CLOSED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['course_group_id'], ['coursegroup.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['period.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['teacher_assignment_id'], ['teacherassignment.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classsession_course_group_id'), 'classsession', ['course_group_id'], unique=False)
    op.create_index(op.f('ix_classsession_id'), 'classsession', ['id'], unique=False)
    op.create_index(op.f('ix_classsession_period_id'), 'classsession', ['period_id'], unique=False)
    op.create_index(op.f('ix_classsession_session_date'), 'classsession', ['session_date'], unique=False)
    op.create_index(op.f('ix_classsession_status'), 'classsession', ['status'], unique=False)
    op.create_index(op.f('ix_classsession_subject_id'), 'classsession', ['subject_id'], unique=False)
    op.create_index(op.f('ix_classsession_teacher_assignment_id'), 'classsession', ['teacher_assignment_id'], unique=False)
    op.create_index(op.f('ix_classsession_teacher_id'), 'classsession', ['teacher_id'], unique=False)
    op.create_table('transfer',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('from_enrollment_id', sa.UUID(), nullable=False),
    sa.Column('to_enrollment_id', sa.UUID(), nullable=False),
    sa.Column('from_campus_id', sa.UUID(), nullable=True),
    sa.Column('to_campus_id', sa.UUID(), nullable=True),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['from_campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['from_enrollment_id'], ['enrollment.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['to_campus_id'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['to_enrollment_id'], ['enrollment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfer_id'), 'transfer', ['id'], unique=False)
    op.create_index(op.f('ix_transfer_student_id'), 'transfer', ['student_id'], unique=False)
    op.create_table('attendancerecord',
    sa.Column('class_session_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_session_id'], ['classsession.id'], ),
    sa.ForeignKeyConstraint(['recorded_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendancerecord_class_session_id'), 'attendancerecord', ['class_session_id'], unique=False)
    op.create_index(op.f('ix_attendancerecord_id'), 'attendancerecord', ['id'], unique=False)
    op.create_index(op.f('ix_attendancerecord_status'), 'attendancerecord', ['status'], unique=False)
    op.create_index(op.f('ix_attendancerecord_student_id'), 'attendancerecord', ['student_id'], unique=False)
    op.create_table('attendancechangelog',
    sa.Column('attendance_record_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('old_status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=True),
    sa.Column('new_status', sa.Enum('PRESENT', 'ABSENT', 'LATE', 'EXCUSED', name='attendancestatus'), nullable=True),
    sa.Column('old_notes', sa.Text(), nullable=True),
    sa.Column('new_notes', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attendance_record_id'], ['attendancerecord.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendancechangelog_attendance_record_id'), 'attendancechangelog', ['attendance_record_id'], unique=False)
    op.create_index(op.f('ix_attendancechangelog_id'), 'attendancechangelog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendancechangelog_id'), table_name='attendancechangelog')
    op.drop_index(op.f('ix_attendancechangelog_attendance_record_id'), table_name='attendancechangelog')
    op.drop_table('attendancechangelog')
    op.drop_index(op.f('ix_attendancerecord_student_id'), table_name='attendancerecord')
    op.drop_index(op.f('ix_attendancerecord_status'), table_name='attendancerecord')
    op.drop_index(op.f('ix_attendancerecord_id'), table_name='attendancerecord')
    op.drop_index(op.f('ix_attendancerecord_class_session_id'), table_name='attendancerecord')
    op.drop_table('attendancerecord')
    op.drop_index(op.f('ix_transfer_student_id'), table_name='transfer')
    op.drop_index(op.f('ix_transfer_id'), table_name='transfer')
    op.drop_table('transfer')
    op.drop_index(op.f('ix_classsession_teacher_id'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_teacher_assignment_id'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_subject_id'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_status'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_session_date'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_period_id'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_id'), table_name='classsession')
    op.drop_index(op.f('ix_classsession_course_group_id'), table_name='classsession')
    op.drop_table('classsession')
    op.drop_index(op.f('ix_teacherassignment_teacher_id'), table_name='teacherassignment')
    op.drop_index(op.f('ix_teacherassignment_subject_id'), table_name='teacherassignment')
    op.drop_index(op.f('ix_teacherassignment_school_year_id'), table_name='teacherassignment')
    op.drop_index(op.f('ix_teacherassignment_id'), table_name='teacherassignment')
    op.drop_index(op.f('ix_teacherassignment_course_group_id'), table_name='teacherassignment')
    op.drop_table('teacherassignment')
    op.drop_index(op.f('ix_student_guardian_student_id'), table_name='student_guardian')
    op.drop_index(op.f('ix_student_guardian_id'), table_name='student_guardian')
    op.drop_index(op.f('ix_student_guardian_guardian_id'), table_name='student_guardian')
    op.drop_table('student_guardian')
    op.drop_index(op.f('ix_idcardissued_is_active'), table_name='idcardissued')
    op.drop_index(op.f('ix_idcardissued_id'), table_name='idcardissued')
    op.drop_index(op.f('ix_idcardissued_card_number'), table_name='idcardissued')
    op.drop_table('idcardissued')
    op.drop_index(op.f('ix_enrollment_student_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_status'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_school_year_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_id'), table_name='enrollment')
    op.drop_index(op.f('ix_enrollment_course_group_id'), table_name='enrollment')
    op.drop_table('enrollment')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_user_campus_user_id'), table_name='user_campus')
    op.drop_index(op.f('ix_user_campus_id'), table_name='user_campus')
    op.drop_index(op.f('ix_user_campus_campus_id'), table_name='user_campus')
    op.drop_table('user_campus')
    op.drop_index(op.f('ix_teacher_user_id'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_teacher_code'), table_name='teacher')
    op.drop_index(op.f('ix_teacher_id'), table_name='teacher')
    op.drop_table('teacher')
    op.drop_index(op.f('ix_student_student_code'), table_name='student')
    op.drop_index(op.f('ix_student_is_active'), table_name='student')
    op.drop_index(op.f('ix_student_id'), table_name='student')
    op.drop_index(op.f('ix_student_document_number'), table_name='student')
    op.drop_index(op.f('ix_student_campus_id'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_period_school_year_id'), table_name='period')
    op.drop_index(op.f('ix_period_id'), table_name='period')
    op.drop_table('period')
    op.drop_index(op.f('ix_idcardtemplate_id'), table_name='idcardtemplate')
    op.drop_table('idcardtemplate')
    op.drop_index(op.f('ix_coursegroup_school_year_id'), table_name='coursegroup')
    op.drop_index(op.f('ix_coursegroup_id'), table_name='coursegroup')
    op.drop_index(op.f('ix_coursegroup_campus_id'), table_name='coursegroup')
    op.drop_table('coursegroup')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_subject_id'), table_name='subject')
    op.drop_index(op.f('ix_subject_code'), table_name='subject')
    op.drop_table('subject')
    op.drop_index(op.f('ix_schoolyear_is_current'), table_name='schoolyear')
    op.drop_index(op.f('ix_schoolyear_id'), table_name='schoolyear')
    op.drop_table('schoolyear')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_guardian_id'), table_name='guardian')
    op.drop_index(op.f('ix_guardian_document_number'), table_name='guardian')
    op.drop_table('guardian')
    op.drop_index(op.f('ix_campus_is_active'), table_name='campus')
    op.drop_index(op.f('ix_campus_id'), table_name='campus')
    op.drop_index(op.f('ix_campus_code'), table_name='campus')
    op.drop_table('campus')
    # ### end Alembic commands ###
