"""add is_active to schoolyear

Revision ID: 1d7d7b281cb5
Revises: f26d1301a338
Create Date: 2026-01-31 14:41:07.981203+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7d7b281cb5'
down_revision = 'f26d1301a338'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schoolyear', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_schoolyear_is_active'), 'schoolyear', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schoolyear_is_active'), table_name='schoolyear')
    op.drop_column('schoolyear', 'is_active')
    # ### end Alembic commands ###
