"""add campus_id to schoolyear

Revision ID: f26d1301a338
Revises: ca2beb40bc2c
Create Date: 2026-01-31 14:39:45.563304+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26d1301a338'
down_revision = 'ca2beb40bc2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schoolyear', sa.Column('campus_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('schoolyear_name_key'), 'schoolyear', type_='unique')
    op.create_index(op.f('ix_schoolyear_campus_id'), 'schoolyear', ['campus_id'], unique=False)
    op.create_foreign_key(None, 'schoolyear', 'campus', ['campus_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schoolyear', type_='foreignkey')
    op.drop_index(op.f('ix_schoolyear_campus_id'), table_name='schoolyear')
    op.create_unique_constraint(op.f('schoolyear_name_key'), 'schoolyear', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('schoolyear', 'campus_id')
    # ### end Alembic commands ###
